name: CICD

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup Go
              uses: actions/setup-go@v2
              with:
                  go-version: '1.15.6'

            - name: Install dependencies
              run: |
                  go version
                  go get -u golang.org/x/lint/golint
                  go get -u github.com/mitchellh/gox

            - name: Install make
              run: |
                  sudo apt install -y make

            # Run vet & lint on the code
            - name: Run vet & lint
              run: |
                  go vet .
                  golint .

            # Run testing on the code
            - name: Run testing
              run: go test -v

            # Build the application
            - name: Run build
              run: make build
